{% set name = "azure-keyvault-secrets" %}
{% set version = "4.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2a03bb2ffd9a0d6c8ad1c330d9d0310113985a9de06607ece378fd72a5889fe1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - typing_extensions >=4.0.1
    - python >=3.7
    - azure-common ~=1.1
    - azure-core >=1.31.0
    - isodate >=0.6.1
    - typing-extensions >=4.0.1

test:
  imports:
    - azure.keyvault.secrets
    - azure.keyvault.secrets.aio

about:
  home: https://docs.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Secret client library for Python
  doc_url: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-secrets/latest/index.html
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-secrets

extra:
  recipe-maintainers:
    - dhirschfeld
